model_name: "HuggingFaceH4/zephyr-7b-gemma-sft-v0.1"
loss_type: "lup"                #   lup | spc | dpo
num_epochs: 1
per_device_batch_size: 1
learning_rate: 3e-5
early_stop_patience: 1
kl_scale: 0.02
js_scale: 0.02
mixture_ratios:
  "argilla/dpo-mix-7k": 1
  "joecodecreations/alpaca_data_52k": 1
  "HuggingFaceH4/ShareGPT_cleaned": 1
  "Anthropic/hh-rlhf": 1
